### ISSUE TITLE
params.trimmer not initialized

### ISSUE THREAD

**Issue by Gianluca-Alessio-Mariani-1512** [nf-core/rnadnavar#66]
### Description of the bug

I am testing the rnadnavar pipeline but it keeps crashing in the parameters initialization because of (probably) a simple bug. When I use the default settings with all the default parameters it says:

[-        ] NFC…EPARE_GENOME:BWAMEM1_INDEX -
[-        ] NFC…EPARE_GENOME:BWAMEM2_INDEX -
[-        ] NFC…E_GENOME:DRAGMAP_HASHTABLE -
[-        ] NFC…4_CREATESEQUENCEDICTIONARY -
[-        ] NFC…PARE_GENOME:SAMTOOLS_FAIDX -
[-        ] NFC…PREPARE_GENOME:TABIX_DBSNP -
[-        ] NFC…ME:TABIX_GERMLINE_RESOURCE -
[-        ] NFC…RE_GENOME:TABIX_KNOWN_SNPS -
[-        ] NFC…_GENOME:TABIX_KNOWN_INDELS -
[-        ] NFC…S:PREPARE_GENOME:TABIX_PON -
[-        ] NFC…GENOME:STAR_GENOMEGENERATE -
[-        ] NFC…_INTERVALS:BUILD_INTERVALS -
[-        ] NFC…RVALS:CREATE_INTERVALS_BED -
[-        ] NFC…_BGZIPTABIX_INTERVAL_SPLIT -
[-        ] NFC…ZIPTABIX_INTERVAL_COMBINED -
[-        ] NFC…NPUT:SAMTOOLS_VIEW_MAP_MAP -
[-        ] NFC…:SAMTOOLS_VIEW_UNMAP_UNMAP -
[-        ] NFC…UT:SAMTOOLS_VIEW_UNMAP_MAP -
[-        ] NFC…UT:SAMTOOLS_VIEW_MAP_UNMAP -
[-        ] NFC…INPUT:SAMTOOLS_MERGE_UNMAP -
Plus 33 more processes waiting for tasks…
WARN: Access to undefined parameter `trimmer` -- Initialise it to a default value eg. `params.trimmer = some_value`
WARN: Unexpected HTTP response.
Failed to send message to https://seqera.ieo.it/api -- received
- status code : 403
- response msg: Unexpected response for request https://seqera.ieo.it/api/trace/572gdzDuiQK6FI/complete?workspaceId=61664385669434
- error cause : -
ERROR ~ Cannot invoke method contains() on null object

 -- Check script 'subworkflows/local/utils_nfcore_rnadnavar_pipeline/main.nf' at line: 219 or see '.nextflow.log' file for more details

But then if I try to add it in the config file:

params {
    // Input options
    input                       = null // sample sheet
    tools                       = null  // List of annotation tools to run - snpeff or vep or merge

    trimmer = "fastp"
}

Following what is set in the subworkflows/local/utils_nfcore_rnadnavar_pipeline/main.nf file:

    def text_preprocessing = [
        "Raw read quality control was performed with FastQC (Andrews 2010)",
        params.trimmer == "fastp" ? "and preprocessing with fastp (Chen et al. 2018)." : "."
    ].join(' ').trim()

It says in the stdout:

...
WARN: The following invalid input values have been detected:

* --trimmer: fastp
...

And it still breaks:

[-        ] NFC…EPARE_GENOME:BWAMEM1_INDEX -
[-        ] NFC…EPARE_GENOME:BWAMEM2_INDEX -
[-        ] NFC…E_GENOME:DRAGMAP_HASHTABLE -
[-        ] NFC…4_CREATESEQUENCEDICTIONARY -
[-        ] NFC…PARE_GENOME:SAMTOOLS_FAIDX -
[-        ] NFC…PREPARE_GENOME:TABIX_DBSNP -
[-        ] NFC…ME:TABIX_GERMLINE_RESOURCE -
[-        ] NFC…RE_GENOME:TABIX_KNOWN_SNPS -
[-        ] NFC…_GENOME:TABIX_KNOWN_INDELS -
[-        ] NFC…S:PREPARE_GENOME:TABIX_PON -
[-        ] NFC…GENOME:STAR_GENOMEGENERATE -
[-        ] NFC…_INTERVALS:BUILD_INTERVALS -
[-        ] NFC…RVALS:CREATE_INTERVALS_BED -
[-        ] NFC…_BGZIPTABIX_INTERVAL_SPLIT -
[-        ] NFC…ZIPTABIX_INTERVAL_COMBINED -
[-        ] NFC…NPUT:SAMTOOLS_VIEW_MAP_MAP -
[-        ] NFC…:SAMTOOLS_VIEW_UNMAP_UNMAP -
[-        ] NFC…UT:SAMTOOLS_VIEW_UNMAP_MAP -
[-        ] NFC…UT:SAMTOOLS_VIEW_MAP_UNMAP -
[-        ] NFC…INPUT:SAMTOOLS_MERGE_UNMAP -
Plus 33 more processes waiting for tasks…
WARN: Unexpected HTTP response.
Failed to send message to https://seqera.ieo.it/api -- received
- status code : 403
- response msg: Unexpected response for request https://seqera.ieo.it/api/trace/4RDrnlG8sIUi4M/complete?workspaceId=61664385669434
- error cause : -
ERROR ~ Cannot invoke method contains() on null object

 -- Check script 'subworkflows/local/utils_nfcore_rnadnavar_pipeline/main.nf' at line: 219 or see '.nextflow.log' file for more details

Attached is the complete log of both cases.

[trimmer_yes_nextflow.log](https://github.com/user-attachments/files/24208281/trimmer_yes_nextflow.log)
[trimmer_no_nextflow.log](https://github.com/user-attachments/files/24208280/trimmer_no_nextflow.log)

### Command used and terminal output

```console

```

**Comment by RaqManzano** [comment]
Hi, 

Thanks a lot for the catch. This is indeed a bug. I fixed it in the #64. Can you use that version and let me know if you have any other issues?

**Comment by Gianluca-Alessio-Mariani-1512** [comment]
The fix would work because I tested it but in the new commit it's still incorrect (probably a typo), because the line:

params.params.trim_fastq || params.split_fastq > 0 ? "and preprocessing with fastp (Chen et al. 2018)." : "."

should be:

params.trim_fastq || params.split_fastq > 0 ? "and preprocessing with fastp (Chen et al. 2018)." : "."

**Comment by RaqManzano** [comment]
Hi Gianluca,

You are very correct, my bad. Fixed now!

Raquel

**Comment by Gianluca-Alessio-Mariani-1512** [comment]
Ok now that problem is gone. 

Just an FYI, in the pipeline log it still gives me other parameter initialization warnings that do not crash the pipeline but I don't think they should be set in the config by the user because I couldn't find them in the parameters section on nf-core/rnadnavar:

WARN: Access to undefined parameter `run_mosdepth` -- Initialise it to a default value eg. `params.run_mosdepth = some_value`
WARN: Access to undefined parameter `run_gatk_preprocessing` -- Initialise it to a default value eg. `params.run_gatk_preprocessing = some_value`
WARN: Access to undefined parameter `run_bcftools` -- Initialise it to a default value eg. `params.run_bcftools = some_value`
WARN: Access to undefined parameter `run_vep` -- Initialise it to a default value eg. `params.run_vep = some_value`
WARN: Access to undefined parameter `run_vcf2maf` -- Initialise it to a default value eg. `params.run_vcf2maf = some_value`

Moreover, since the pipeline now works after that point, I encountered a crash in another step, I will open a new bug report because i don't think it is related to any of these parameter initialization.

**Comment by RaqManzano** [comment]
Hi Gianluca, I am going to close this issue and add to my todo list to remove those warnings. Thanks
